# fly.toml app configuration file generated for next-js-memory-leak-reproduction-example on 2023-06-02T12:12:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "next-js-memory-leak-reproduction-example"
primary_region = "otp"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
