import './globals.css';
import Link from 'next/link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Link href="/">Home</Link>
          <Link href="/page2">page 2</Link>
          <Link href="/page3">page 3</Link>
          <Link href="/page4">page 4</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
